### ISSUE TITLE
aruco single not working on indigo

### ISSUE THREAD

**Issue by vannem95** [pal-robotics/aruco_ros#38]
This was working fine on kinetic. I needed it on indigo. Here are the launch files and the errors i am getting. 
Anyone know what the issue might be?

Thanks in advance.

![main_error](https://user-images.githubusercontent.com/14225433/33917351-a19d7c28-df62-11e7-9134-970a85c67bb3.png)
![single_and_usbcamstream](https://user-images.githubusercontent.com/14225433/33917352-a1b51e64-df62-11e7-9f7c-d392ed202a06.png)

**Comment by bmagyar** [comment]
Not really...Actually the current version should support Indigo more and is
less ideal for Kinetic.

**Comment by LeLiPepsi** [comment]
Hi there, I am doing some experiments with aruco on PR2(indigo). After launching "single.launch", I got exactly the same error. Did you guys already have solution for this problem? ;)
Thanks

**Comment by LeLiPepsi** [comment]
Hi guys, I might have figured out the reason for this problem. It seems that we clone the pkg from kinetic branch instead of indigo branch. So the codes will not work in indigo. Just try the following command to clone the correct branch to workspace and compile again. It works for me. ;)

$ git clone -b indigo-devel https://github.com/pal-robotics/aruco_ros.git
